MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.15                                                   # [x86_64 and osx]
  - 13.3                                                    # [arm64 and osx]
