numpy:
  - 2

python_impl:
  - cpython

python:
  - 3.11
  - 3.12

blas:
  - openblas            # [linux]
  - libaccelerate-osx   # [osx]

lapack:
  - openblas            # [linux]
  - libaccelerate-osx   # [osx]
