MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.15                                                   # [x86_64 and osx]
  - 11.3                                                    # [arm64 and osx]

c_compiler:
    - gcc             # [linux]
    - clang           # [osx]
c_compiler_version:
    - 15              # [linux]
    - 20              # [osx]

cxx_compiler:
    - gxx             # [linux]
    - clangxx         # [osx]
cxx_compiler_version:
    - 15              # [linux]
    - 20              # [osx]

fortran_compiler:
  - gfortran
fortran_compiler_version:
  - 15

mpi_type:
  - conda
libfabric:
  - "1.19"
libpmix_devel:
  - "5"