MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.15                                                   # [x86_64 and osx]
  - 11.3                                                    # [arm64 and osx]

c_compiler:
    - gcc             # [linux]
    - clang           # [osx]
c_compiler_version:
    - 14              # [linux]
    - 20              # [osx]

cxx_compiler:
    - gxx             # [linux]
    - clangxx         # [osx]
cxx_compiler_version:
    - 14              # [linux]
    - 20              # [osx]

fortran_compiler:
  - gfortran
fortran_compiler_version:
  - 14

libfabric:
  # build against libfabric 1.19
  # for compatibility with ABI 1.6 (libfabric 1.14)
  # this is forward-compatible with libfabric 2.x
  - "1.19"

mpi_type:
  - conda
